apiVersion: v1
kind: ConfigMap
metadata:
  name: agentcore-config
  namespace: apps
data:
  memory-id: "{MEMORY_ID}"
  aws-region: "ap-northeast-1"
  gateway-url: "https://{GATEWAY_ID}.gateway.bedrock-agentcore.ap-northeast-1.amazonaws.com/mcp"
  gateway-token-endpoint: "https://agentcore-d046cb6e.auth.ap-northeast-1.amazoncognito.com/oauth2/token"
